trainer: AgentTrainer
trainer_kwargs:
  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 1500000
    batch_size: 128 # 1024
    sample_strategy: uniform  # potentially update to PER or other
    save_frequency: 100000

  optimizer_class: Adam
  optimizer_kwargs:
    actor_optimizer_kwargs:
      lr: 0.0001
    critic_optimizer_kwargs:
      lr: 0.001
    log_alpha_optimizer_kwargs:
      lr: 0.00000001
      # use SAC/AgentTrainer to 
      # 1. supervise Q
      # 2. supervise actor 
      # 3. perform SAC as usual
      # keep the alpha stuff but keep initial temperature very low

  num_pretrain_steps: 0
  num_train_steps: 0
  num_critic_only_train_steps: 500000
  num_actor_only_train_steps: 150000
  num_original_train_steps: 50000
  num_val_steps: 1000
  val_freq: 10000
  num_eval_episodes: 100
  eval_freq: 1000
  checkpoint_freq: 50000
  log_freq: 1000
  profile_freq: 100

  dataset_checkpoints: 
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_0/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_1/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_2/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_3/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_4/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_5/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_6/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_7/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_8/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_9/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_10/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_11/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_12/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_13/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_14/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_15/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_16/train_data/
    # - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_17/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_18/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_19/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_20/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_21/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_22/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_23/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_24/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_25/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_26/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_27/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_28/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_29/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_30/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_31/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_32/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_33/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_34/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_35/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_36/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_37/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_38/train_data/
    - models/20230105/dataset_collection/min3_max4_num_box_obj/pick_39/train_data/

  val_dataset_checkpoints: 
    - models/20221231/dataset_collection/pick_100/train_data/
