trainer: AgentTrainer
trainer_kwargs:
  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 1300000
    batch_size: 128 # 1024
    sample_strategy: uniform  # potentially update to PER or other
    save_frequency: 100000

  optimizer_class: Adam
  optimizer_kwargs:
    actor_optimizer_kwargs:
      lr: 0.0001
    critic_optimizer_kwargs:
      lr: 0.0001
    log_alpha_optimizer_kwargs:
      lr: 0.00000001
      # use SAC/AgentTrainer to 
      # 1. supervise Q
      # 2. supervise actor 
      # 3. perform SAC as usual
      # keep the alpha stuff but keep initial temperature very low

  num_pretrain_steps: 0
  num_train_steps: 0
  num_critic_only_train_steps: 150000
  num_actor_only_train_steps: 150000
  num_original_train_steps: 50000
  num_val_steps: 1000
  val_freq: 10000
  num_eval_episodes: 100
  eval_freq: 1000
  checkpoint_freq: 50000
  log_freq: 1000
  profile_freq: 100
  
  # place_11
  # pull_2 
  # push_100
  
  dataset_checkpoints: 
    - models/20221231/dataset_collection/place_0/train_data/
    - models/20221231/dataset_collection/place_1/train_data/
    - models/20221231/dataset_collection/place_2/train_data/
    - models/20221231/dataset_collection/place_3/train_data/
    - models/20221231/dataset_collection/place_4/train_data/
    - models/20221231/dataset_collection/place_5/train_data/
    - models/20221231/dataset_collection/place_6/train_data/
    - models/20221231/dataset_collection/place_7/train_data/
    - models/20221231/dataset_collection/place_8/train_data/
    - models/20221231/dataset_collection/place_9/train_data/
    - models/20221231/dataset_collection/place_10/train_data/
    - models/20221231/dataset_collection/place_11/train_data/
    # - models/20221231/dataset_collection/place_12/train_data/
    # - models/20221231/dataset_collection/place_13/train_data/
    # - models/20221231/dataset_collection/place_14/train_data/
    # - models/20221231/dataset_collection/place_15/train_data/
    # - models/20221231/dataset_collection/place_16/train_data/
    # - models/20221231/dataset_collection/place_17/train_data/
    # - models/20221231/dataset_collection/place_18/train_data/
    # - models/20221231/dataset_collection/place_19/train_data/
    # - models/20221231/dataset_collection/place_20/train_data/
    # - models/20221231/dataset_collection/place_21/train_data/
    # - models/20221231/dataset_collection/place_22/train_data/
    # - models/20221231/dataset_collection/place_23/train_data/
    # - models/20221231/dataset_collection/place_24/train_data/

  val_dataset_checkpoints: 
    - models/20221231/dataset_collection/place_100/train_data/
