trainer: DafTrainer
trainer_kwargs:
  dynamics_trainer_config: configs/pybox2d/trainers/dynamics.yaml
  agent_trainer_config: configs/pybox2d/trainers/agent.yaml

  sample_primitive_actions: false

  num_pretrain_steps: 1000
  num_train_steps: 50000
  num_eval_steps: 100
  eval_freq: 1000
  checkpoint_freq: 50000
  log_freq: 1000
  profile_freq: 100
