trainer: AgentTrainer
trainer_kwargs:
  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 200000
    batch_size: 128
    sample_strategy: uniform
    save_frequency: 1000

  optimizer_class: Adam
  optimizer_kwargs:
    actor_optimizer_kwargs:
      lr: 0.0001
    critic_optimizer_kwargs:
      lr: 0.0001
    log_alpha_optimizer_kwargs:
      lr: 0.0001

  num_pretrain_steps: 200000
  num_train_steps: 0
  num_eval_episodes: 0
  eval_freq: 0
  checkpoint_freq: 10000
  log_freq: 1000
  profile_freq: 1000
