trainer: ValueTrainer
trainer_kwargs:
  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 800000
    batch_size: 128
    sample_strategy: uniform

  optimizer_class: Adam
  optimizer_kwargs:
    lr: 0.0001

  num_train_steps: 200000
  num_eval_steps: 1000
  eval_freq: 1000
  checkpoint_freq: 10000
  log_freq: 1000
  profile_freq: 100
