planner: NonPlanner 
planner_kwargs:
  default_actor: policy
  default_dynamics: ground_truth

task: 
  - env: "PlaceRight2D"
    opt: [1]
    dep: [[]]

  - env: "PushLeft2DControl"
    opt: []
    dep: []
