planner: ShootingPlanner
planner_kwargs:
  default_actor: policy
  default_critic: q_fn
  default_model: ground_truth
  samples: 100
  standard_deviation: 0.5

task: 
  - env: "PlaceRight2D"
    opt: [1]
    dep: [[]]

  - env: "PushLeft2DControl"
    opt: []
    dep: []
