planner: ShootingPlanner
planner_kwargs:
  default_actor: random
  default_critic: q_fn
  default_model: ground_truth
  samples: 100

task: 
  - env: "PlaceRight2D"
    opt: [1]
    dep: [[]]

  - env: "PushLeft2DControl"
    opt: []
    dep: []
