name: temporal_policies
channels:
  - pytorch
  - conda-forge
  - nvidia
  - default
dependencies:
  - python=3.8
  
  # pytorch
  - pytorch
  - cudatoolkit=11.1
  - torchvision
  - torchtext

  # NP Family
  - numpy
  - scipy
  - networkx
  - scikit-image

  # Environment
  - pybox2d

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  - pip
  - pip:
      - gym>=0.12
      - pygame
