[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "temporal_policies"
version = "0.0.1"
authors = [
  { name = "Christopher Agia", email = "cagia@cs.stanford.edu" },
  { name = "Toki Migimatsu", email = "takatoki@cs.stanford.edu" }
]
description = "Learning compositional policies for long horizon planning."
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  # NumPy Family
  "numpy",
  "scipy",
  "scikit-image",
  # IO
  "imageio",
  "pillow",
  "pyyaml",
  "tensorboard",
  # Other
  "tqdm",
  # Env
  "gym>=0.12,<0.25",
  "box2d-py",
  # PyTorch
  "torch==1.11",
]

[tools.setuptools]
packages = ["temporal_policies"]
