env: pybullet.HumanTableEnv
env_kwargs:
  name: hook_handover_0
  gui: true

  primitives:
    - pick
    - place
    - static_handover

  tasks:
    - action_skeleton:
        - pick(red_box, table)
        - static_handover(red_box, right_hand)
      initial_state:
        - free(hook)
        - free(red_box)
        - inworkspace(hook)
        - on(hook, table)
        - on(red_box, table)
        
  robot_config: configs/pybullet/envs/robots/safe_franka_panda_sim.yaml
  human_config: configs/pybullet/envs/humans/average_male_TUM.yaml
  animation_type: HumanRobotHandover
  animation_frequency: 100
  visualize_shield: false

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - configs/pybullet/envs/assets/milk.yaml
