env: pybullet.TableEnv
env_kwargs:
  name: place
  gui: true

  primitives:
    - place
  
  tasks:
    - action_skeleton:
        - place(a, table)
      initial_state:
        - inhand(a)
        - on(rack, table)
        - on(b, table)
        - on(c, table)
        - on(d, table)
        - on(e, rack)
        - on(f, rack)
        - on(g, rack)
        - istippable(b)
        - istippable(e)
    - action_skeleton:
      - place(d, rack)
      initial_state:
        - inhand(d)
        - on(rack, table)
        - on(a, table)
        - on(b, table)
        - on(c, table)
        - on(e, rack)
        - on(f, rack)
        - on(g, rack)
        - istippable(a)
        - istippable(e)
        
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  object_groups:
    - name: movable
      objects:
      - object_type: Box
        object_kwargs:
          size: [0.05, 0.025, 0.1]
          color: [1.0, 0.0, 0.0, 1.0]
      - object_type: Box
        object_kwargs:
          size: [0.05, 0.05, 0.1]
          color: [1.0, 0.0, 0.0, 1.0]
      - object_type: Box
        object_kwargs:
          size: [0.025, 0.025, 0.1]
          color: [0.0, 0.0, 1.0, 1.0]
      - object_type: Hook
        object_kwargs:
          head_length: 0.2
          handle_length: 0.38
          handle_y: -1.0
          color: [0.4, 0.2, 0.0, 1.0]
      - object_type: Null
      - object_type: Null
      - object_type: Null

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Variant
      object_kwargs:
        name: a
        group: movable
    - object_type: Variant
      object_kwargs:
        name: b
        group: movable
    - object_type: Variant
      object_kwargs:
        name: c
        group: movable
    - object_type: Variant
      object_kwargs:
        name: d
        group: movable
    - object_type: Variant
      object_kwargs:
        name: e
        group: movable
    - object_type: Variant
      object_kwargs:
        name: f
        group: movable
    - object_type: Variant
      object_kwargs:
        name: g
        group: movable
