robot_name: "panda"

# Failsafe information
max_s_stop: 0.2
q_min_allowed: [-2.89, -1.76, -2.89, -3.05, -2.89, -0.01, -2.89]
q_max_allowed: [2.89, 1.76, 2.89, -0.06, 2.89, 3.75, 2.89]
v_max_allowed: [2.1750, 2.1750, 2.1750, 2.1750, 2.610, 2.610, 2.610]
a_max_allowed: [50, 50, 50, 50, 50, 50, 50]
j_max_allowed: [800, 800, 800, 800, 800, 800, 800]
# Maximum long-term planning acc / jerk
a_max_ltt: [10, 10, 10, 10, 10, 10, 10]
j_max_ltt: [30, 30, 30, 30, 30, 30, 30]

nb_joints: 7

q1: [0.0]
q2: [0.0]
q3: [0.0]
q4: [0.0]
q5: [0.0]
q6: [0.0]
q7: [0.0]

alpha_i_max: 5.0

# safety-rated speed specified by iso-norm
v_safe: 0.05

# APPROXIMATE == 0
# EXACT == 1
velocity_method: 0