env: pybullet.TableEnv
env_kwargs:
  name: pick
  gui: true

  primitives:
    - pick

  tasks:
    - prob: 0.25
      action_skeleton:
        - pick(a, table)
      initial_state:
        - on(rack, table)
        - on(hook, table)
        - on(a, table)
        - on(b, table)
        - on(c, rack)
        - on(d, rack)
    - prob: 0.25
      action_skeleton:
        - pick(c, rack)
      initial_state:
        - on(rack, table)
        - on(hook, table)
        - on(a, table)
        - on(b, table)
        - on(c, rack)
        - on(d, rack)
    - prob: 0.5
      action_skeleton:
        - pick(hook, table)
      initial_state:
        - on(rack, table)
        - on(hook, table)
        - on(a, table)
        - on(b, table)
        - on(c, rack)
        - on(d, rack)
    - prob: 0.25
      action_skeleton:
        - pick(a, table)
      initial_state:
        - inworkspace(a)
        - on(rack, table)
        - on(hook, table)
        - on(a, table)
        - on(b, table)
        - on(c, rack)
        - on(d, rack)
    - prob: 0.25
      action_skeleton:
        - pick(c, rack)
      initial_state:
        - inworkspace(rack)
        - inworkspace(c)
        - on(rack, table)
        - on(hook, table)
        - on(a, table)
        - on(b, table)
        - on(c, rack)
        - on(d, rack)
    - prob: 0.5
      action_skeleton:
        - pick(hook, table)
      initial_state:
        - inworkspace(hook)
        - on(rack, table)
        - on(hook, table)
        - on(a, table)
        - on(b, table)
        - on(c, rack)
        - on(d, rack)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  object_groups:
    - name: boxes
      objects:
        - object_type: Box
          object_kwargs:
            size: [0.05, 0.05, 0.1]
            color: [1.0, 0.0, 0.0, 1.0]
        - object_type: Box
          object_kwargs:
            size: [0.1, 0.05, 0.1]
            color: [0.0, 0.0, 1.0, 1.0]
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Variant
      object_kwargs:
        name: rack
        variants:
          - object_type: Rack
            object_kwargs:
              size: [0.22, 0.32, 0.16]
              color: [0.4, 0.2, 0.0, 1.0]
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: hook
        variants:
          - object_type: Hook
            object_kwargs:
              head_length: 0.2
              handle_length: 0.38
              handle_y: -1.0
              color: [0.4, 0.2, 0.0, 1.0]
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: a
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: b
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: c
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: d
        group: boxes
