env: pybullet.HumanTableEnv
env_kwargs:
  name: human_template_env
  gui: true

  primitives:
    - pick
    - place
    - static_handover

  tasks:
    - action_skeleton:
         - pick(icecream)
         - static_handover(icecream, right_hand)
      initial_state:
        # - on(rack, table)
        - on(hook, table)
        - on(icecream, table)

  robot_config: configs/pybullet/envs/robots/safe_franka_panda_sim.yaml
  human_config: configs/pybullet/envs/humans/average_male_TUM.yaml
  animation_type: HumanRobotHandover
  animation_frequency: 100
  visualize_shield: false
  # human_animation_names: ["0"]

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    # - object_type: Rack
    #   object_kwargs:
    #     name: rack
    #     size: [0.22, 0.32, 0.16]
    #     color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Variant
      object_kwargs:
        name: hook
        variants:
          - object_type: Hook
            object_kwargs:
              name: _hook
              head_length: 0.2
              handle_length: 0.38
              handle_y: -1.0
              color: [0.6, 0.6, 0.6, 1.0]
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: icecream
        variants:
          - configs/pybullet/envs/assets/icecream.yaml
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: milk
        variants:
          - configs/pybullet/envs/assets/milk.yaml
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: salt
        variants:
          - configs/pybullet/envs/assets/salt.yaml
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: yogurt
        variants:
          - configs/pybullet/envs/assets/yogurt.yaml
          - object_type: Null
