env: pybullet.TableEnv
env_kwargs:
  name: place
  gui: true

  primitives:
    - place

  tasks:
    - action_skeleton:
        - place(box, table)
      initial_state:
        - inhand(box)
        - on(rack, table)
        - inworkspace(rack)
        # - on(hook, table)
        # - istippable(hook)
    - action_skeleton:
        - place(box, rack)
      initial_state:
        - inhand(box)
        - on(rack, table)
        - inworkspace(rack)
        # - on(hook, table)
        # - istippable(hook)
    # - action_skeleton:
    #     - place(hook, table)
    #   initial_state:
    #     - inhand(hook)
    #     - on(box, table)
    #     - istippable(box)
    #     - on(rack, table)
    #     - inworkspace(rack)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]  # Larger rack.
        # size: [0.21, 0.32, 0.14]  # Smaller rack.
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Box
      object_kwargs:
        name: box
        size: [0.05, 0.05, 0.1]
        color: [1.0, 0.0, 0.0, 1.0]
    # - object_type: Hook
    #   object_kwargs:
    #     name: hook
    #     head_length: 0.2
    #     handle_length: 0.38
    #     handle_y: -1.0
    #     color: [0.4, 0.2, 0.0, 1.0]
