# YAML can be used for both pretraining and non-pretraining
agent: SAC
agent_kwargs:
  tau: 0.005  # don't use target in 1 step envs
  initial_temperature: 1e-6  # assume large dataset with multi-stage training + supervised Q already
  critic_update_freq: 1
  actor_update_freq: 1
  target_update_freq: 1e8  # don't use target in 1 step envs

  actor_class: actors.DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers: [256, 256]
    log_std_bounds: [-5, 2]
    ortho_init: true

  critic_class: critics.ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [256, 256]
    num_q_fns: 2
    ortho_init: true
    output_act: Sigmoid

  encoder_class: encoders.TableEnvEncoder
