planner: ShootingPlanner
planner_kwargs:
  num_samples: 128

agent_configs:
  - agent: GaussianAgent
    agent_kwargs:
      agent_config: configs/pybox2d/agents/sac.yaml
      std: 0.5
  - configs/pybox2d/agents/sac.yaml

dynamics_config:
  dynamics: OracleDynamics
