planner: ShootingPlanner
planner_kwargs:
  num_samples: 128

agent_configs:
  - agent: GaussianAgent
    agent_kwargs:
      std: 0.5
      agent_config:
        agent: SCODCriticAgent
        agent_kwargs:
          agent_config: "{AGENT_CONFIG}"
          scod: VaRSCOD
          scod_config: "{SCOD_CONFIG}"
          scod_kwargs:
            alpha: 0.9
  - agent: SCODCriticAgent
    agent_kwargs:
      scod: VaRSCOD
      scod_config: "{SCOD_CONFIG}"
      scod_kwargs: 
        alpha: 0.9
      agent_config: "{AGENT_CONFIG}"

dynamics_config:
  dynamics: OracleDynamics
