planner: ShootingPlanner
planner_kwargs:
  num_samples: 128

agent_configs:
  - agent: OracleAgent
    agent_kwargs:
      agent_config:
        agent: GaussianAgent
        agent_kwargs:
          agent_config: configs/pybox2d/agents/sac.yaml
          std: 0.5
  - agent: OracleAgent
    agent_kwargs:
      agent_config: configs/pybox2d/agents/sac.yaml

dynamics_config: configs/pybox2d/dynamics/decoupled.yaml
