planner: ShootingPlanner
planner_kwargs:
  num_samples: 128

agent_configs:
  - agent: RandomAgent
    agent_kwargs:
      agent_config:
        agent: OracleAgent
        agent_kwargs:
          agent_config: configs/pybox2d/agents/sac.yaml
  - agent: OracleAgent
    agent_kwargs:
      agent_config: configs/pybox2d/agents/sac.yaml

dynamics_config:
  dynamics: OracleDynamics
