planner: CEMPlanner
planner_kwargs:
  random_initialization: true
  num_samples: 16
  num_iterations: 8

agent_configs:
  - agent: OracleAgent
    agent_kwargs:
      agent_config: configs/pybox2d/agents/sac.yaml
  - agent: OracleAgent
    agent_kwargs:
      agent_config: configs/pybox2d/agents/sac.yaml

dynamics_config: configs/pybox2d/dynamics/decoupled.yaml
