env: pybullet.TableEnv
env_kwargs:
  name: structured_language_2
  gui: false

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - instruction: How would you pick and place the yellow box and blue box onto the table, then use the hook to push the cyan box under the rack?
      action_skeleton:
        - pick(yellow_box)
        - place(yellow_box, table)
        - pick(hook)
        - push(yellow_box, hook, rack)
      initial_state:
        - free(hook)
        - free(cyan_box)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(hook)
        - beyondworkspace(rack)
        - nonblocking(rack, cyan_box)
        - nonblocking(rack, yellow_box)
        - inobstructionzone(yellow_box)
        - inobstructionzone(blue_box)
        - infront(yellow_box, rack)
        - infront(blue_box, rack)
        - inoperationalzone(cyan_box)
        - infront(cyan_box, rack)
        - on(rack, table)
        - on(hook, table)
        - on(cyan_box, table)
        - on(yellow_box, table)
        - on(blue_box, table)
      goal_propositions:
        - ["under(cyan_box, rack)"]
      supported_predicates:
        - under(a, b)
        - on(a, b)
        - inhand(a)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - configs/pybullet/envs/assets/icecream.yaml
    - configs/pybullet/envs/assets/yogurt.yaml
    - configs/pybullet/envs/assets/salt.yaml
