name: temporal_policies

channels:
  - pytorch
  - conda-forge
  - default

dependencies:
  - python=3.8

  # NP Family
  - numpy
  - scipy
  - networkx
  - scikit-image

  # Environment
  - pybox2d

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  - pip
  - pip:
      - -r requirements_arm64.txt