dynamics: DecoupledDynamics
dynamics_kwargs:
  network_class: MLPDynamics
  network_kwargs:
    dim_latent: 17
    hidden_layers: [256, 256]
    ortho_init: true

  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 1000000
    batch_size: 1024
    sample_strategy: uniform

  optimizer_class: Adam
  optimizer_kwargs:
    lr: 0.001

train_kwargs:
  total_steps: 20000
  log_freq: 250
  eval_freq: 10000
  workers: 0
  profile_freq: 50
