planner: CEMPlanner
planner_kwargs:
  num_samples: 200
  num_iterations: 5
  num_elites: 20
  standard_deviation: 0

agent_configs:
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"

dynamics_config: "{DYNAMICS_CONFIG}"
