planner: CEMPlanner
planner_kwargs:
  num_samples: 16
  num_iterations: 8
  standard_deviation: 0.1

agent_configs:
  - "{AGENT_CONFIG}"
  - "{AGENT_CONFIG}"
  - "{AGENT_CONFIG}"

dynamics_config:
  dynamics: OracleDynamics
  dynamics_kwargs:
    debug: false
