planner: CEMPlanner
planner_kwargs:
  num_samples: 10000
  num_iterations: 5
  num_elites: 100
  keep_elites_fraction: 1.0
  standard_deviation: 0.3
  std_decay: 0.6

agent_configs:
  - "{AGENT_CONFIG}"
  - "{AGENT_CONFIG}"
  - "{AGENT_CONFIG}"
  - "{AGENT_CONFIG}"

dynamics_config: "{DYNAMICS_CONFIG}"

custom_fns:
  pick: "ScrewdriverPickFn"
  place: null
  static_handover: "HandoverOrientationFn"