planner: CEMPlanner
planner_kwargs:
  num_samples: 16
  num_iterations: 8
  standard_deviation: 0.3

agent_configs:
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"

dynamics_config:
  dynamics: OracleDynamics
  dynamics_kwargs:
    debug: false
