name: "AverageMale"
color: [0.706, 0.541, 0.471, 1.0]

body_names:
  - "head"
  - "torso"
  - "left_upper_arm"
  - "left_lower_arm"
  - "left_hand"
  - "right_upper_arm"
  - "right_lower_arm"
  - "right_hand"

body_measurement_ids:
  head: [1, 2]
  torso: [0, 1]
  left_upper_arm: [3, 4]
  left_lower_arm: [4, 8]
  left_hand: [8, 8]
  right_upper_arm: [5, 6]
  right_lower_arm: [6, 7]
  right_hand: [7, 7]

body_radii:
  head: 0.1
  torso: 0.17
  left_upper_arm: 0.047
  left_lower_arm: 0.035
  left_hand: 0.1
  right_upper_arm: 0.047
  right_lower_arm: 0.035
  right_hand: 0.1

body_lengths:
  head: 0.1
  torso: 0.35
  left_upper_arm: 0.3
  left_lower_arm: 0.3
  left_hand: 0.0
  right_upper_arm: 0.3
  right_lower_arm: 0.3
  right_hand: 0.0