env: pybullet.TableEnv
env_kwargs:
  name: structured_language_1
  gui: false

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - instruction: How would you pick and place the yellow box, cyan box and blue box onto the rack?

      action_skeleton:
        - pick(yellow_box)
        - place(yellow_box, rack)
        - pick(cyan_box)
        - place(cyan_box, rack)
        - pick(blue_box)
        - place(blue_box, rack)
      initial_state:
        - free(yellow_box)
        - free(cyan_box)
        - free(blue_box)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(rack)
        - inworkspace(yellow_box)
        - inworkspace(cyan_box)
        - inworkspace(blue_box)
        - on(rack, table)
        - on(yellow_box, table)
        - on(cyan_box, table)
        - on(blue_box, table)

      goal_propositions:
        - ["on(yellow_box, rack)" , "on(cyan_box, rack)", "on(blue_box, rack)"]
      supported_predicates:
        - under(a, b)
        - on(a, b)
        - inhand(a)
        
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - configs/pybullet/envs/assets/salt.yaml
    - configs/pybullet/envs/assets/yogurt.yaml
    - configs/pybullet/envs/assets/icecream.yaml
